import type { Referral, Resource, Worker } from "./types";

export const workers: Worker[] = [
  {
    id: "maya",
    slug: "maya",
    firstName: "Maya",
    pronouns: "she/her",
    bio: "A qualified youth worker who can help you untangle housing, work and study options. Clear, practical and no judgement.",
    supportedTopics: ["Housing or somewhere safe", "Work", "Study or training", "I am not sure"],
    formats: ["phone", "video", "text", "in-person"],
    qualificationStatus: "Qualifications checked for demonstration pilot",
    image: "/images/fs_youth-worker.jpg",
  },
  {
    id: "alex",
    slug: "alex",
    firstName: "Alex",
    pronouns: "they/them",
    bio: "A qualified youth worker focused on money, food, transport and getting ready for paid work.",
    supportedTopics: ["Money", "Food or transport", "Resume or interviews", "Work"],
    formats: ["phone", "video", "text"],
    qualificationStatus: "Qualifications checked for demonstration pilot",
    image: "/images/fs_img_2.jpg",
  },
];

export const resources: Resource[] = [
  {
    id: "housing-line",
    slug: "victoria-homelessness-support",
    title: "Victoria statewide homelessness support",
    organisation: "Victorian homelessness support line",
    summary: "Call for 24-hour help if you need somewhere safe to stay or are at risk of homelessness.",
    description: "This statewide line connects people in Victoria with local housing and homelessness services. It is an external service, not operated by first_step.",
    category: "Safe place tonight",
    urgency: "urgent",
    formats: ["phone"],
    age: "All ages",
    location: "Victoria",
    cost: "Call costs may apply",
    nextStep: "Call 1800 825 955. If someone is in immediate danger, call 000.",
    contact: "You will speak with an external housing support service.",
    openingHours: "24 hours, every day",
    phone: "1800825955",
    status: "active",
    sourceType: "verified_external",
    lastVerifiedAt: "2026-07-21",
    noReferral: true,
  },
  {
    id: "kids-helpline",
    slug: "kids-helpline",
    title: "Kids Helpline",
    organisation: "Kids Helpline",
    summary: "Free, private and confidential support for young people aged 5–25.",
    description: "Talk by phone or use online support. Kids Helpline is an external service and is available around the clock.",
    category: "Talk to someone",
    urgency: "urgent",
    formats: ["phone", "online"],
    age: "5–25",
    location: "Australia",
    cost: "Free",
    nextStep: "Call 1800 55 1800 or visit the official website.",
    contact: "A Kids Helpline counsellor will respond.",
    openingHours: "24 hours, every day",
    website: "https://kidshelpline.com.au/",
    phone: "1800551800",
    status: "active",
    sourceType: "verified_external",
    lastVerifiedAt: "2026-07-21",
    noReferral: true,
  },
  {
    id: "respect",
    slug: "1800respect",
    title: "1800RESPECT",
    organisation: "1800RESPECT",
    summary: "Domestic, family and sexual violence support by phone, text or online chat.",
    description: "A national external service for anyone affected by domestic, family or sexual violence, including people supporting someone else.",
    category: "Family violence",
    urgency: "urgent",
    formats: ["phone", "online"],
    age: "All ages",
    location: "Australia",
    cost: "Free",
    nextStep: "Call 1800 737 732 or text 0458 737 732.",
    contact: "A trained 1800RESPECT counsellor will respond.",
    openingHours: "24 hours, every day",
    website: "https://www.1800respect.org.au/",
    phone: "1800737732",
    status: "active",
    sourceType: "verified_external",
    lastVerifiedAt: "2026-07-21",
    noReferral: true,
  },
  {
    id: "lifeline",
    slug: "lifeline",
    title: "Lifeline",
    organisation: "Lifeline Australia",
    summary: "24-hour crisis support by phone, text and online chat.",
    description: "Lifeline is an external crisis support service. Call 000 if life is in immediate danger.",
    category: "Talk to someone",
    urgency: "urgent",
    formats: ["phone", "online"],
    age: "All ages",
    location: "Australia",
    cost: "Free support",
    nextStep: "Call 13 11 14.",
    contact: "A Lifeline crisis supporter will respond.",
    openingHours: "24 hours, every day",
    website: "https://www.lifeline.org.au/",
    phone: "131114",
    status: "active",
    sourceType: "verified_external",
    lastVerifiedAt: "2026-07-21",
    noReferral: true,
  },
  {
    id: "tafe-pathway",
    slug: "tafe-and-vce-vm-options",
    title: "Explore TAFE and VCE VM options",
    organisation: "first_step pathway guide",
    summary: "Compare practical study and training routes without committing today.",
    description: "A demonstration guide to questions you can ask a TAFE or VCE VM provider. Course details and eligibility must be checked with the provider.",
    category: "Study and training",
    urgency: "anytime",
    formats: ["online", "phone", "in-person"],
    age: "16–25",
    location: "Victoria",
    cost: "Course costs vary; fee support may be available",
    nextStep: "Save the questions or book a youth worker to compare your options.",
    contact: "No one contacts you unless you choose to book.",
    openingHours: "Browse any time",
    status: "active",
    sourceType: "demonstration",
    lastVerifiedAt: "2026-07-10",
    noReferral: true,
  },
  {
    id: "paid-work",
    slug: "paid-work-readiness",
    title: "Paid work readiness pathway",
    organisation: "first_step demonstration partner pathway",
    summary: "Get practical help with a résumé, interview or a path into properly paid work.",
    description: "Demonstration content inspired by Victorian social enterprises. All productive work must be paid, or be a lawful and formally structured vocational placement.",
    category: "Work and paid opportunities",
    urgency: "soon",
    formats: ["online", "in-person"],
    age: "16–25",
    location: "Melbourne pilot area",
    cost: "No cost to browse",
    nextStep: "Book a youth worker to check fit and current availability.",
    contact: "No one contacts you until you consent.",
    openingHours: "Demonstration pathway only",
    status: "active",
    sourceType: "future_partner",
    lastVerifiedAt: "2026-07-01",
    noReferral: false,
  },
  {
    id: "food-transport",
    slug: "food-and-transport-options",
    title: "Food and transport options",
    organisation: "first_step local guide",
    summary: "Start with nearby food relief, travel support and concession checks.",
    description: "A demonstration local guide. A youth worker can help confirm what is currently available in your area.",
    category: "Food and transport",
    urgency: "soon",
    formats: ["online", "phone", "in-person"],
    age: "16–25",
    location: "Victoria",
    cost: "Many listed supports are free",
    nextStep: "Choose your area or talk to a worker.",
    contact: "No automatic contact.",
    openingHours: "Varies by service",
    status: "active",
    sourceType: "demonstration",
    lastVerifiedAt: "2026-06-25",
    noReferral: true,
  },
  {
    id: "money-help",
    slug: "money-next-steps",
    title: "Sort the next money step",
    organisation: "first_step money guide",
    summary: "A short checklist for bills, concessions, debts and free financial counselling.",
    description: "This demonstration guide avoids asking for account details. A qualified financial counsellor should handle personal financial advice.",
    category: "Money and financial stability",
    urgency: "soon",
    formats: ["online", "phone"],
    age: "16–25",
    location: "Australia",
    cost: "Free to browse",
    nextStep: "Choose one bill or question to start with.",
    contact: "No one contacts you unless you book.",
    openingHours: "Browse any time",
    status: "needs_review",
    sourceType: "demonstration",
    lastVerifiedAt: "2026-04-12",
    noReferral: true,
  },
];

export const seedReferrals: Referral[] = [
  {
    id: "ref-1",
    appointmentId: "seed-appt",
    workerId: "maya",
    partnerName: "Northside Youth Pathways",
    partnerSummary: "Demonstration partner providing study and paid-work navigation.",
    sharedFields: ["Chosen first name", "Safe email", "Age band", "Study and work topics"],
    approvedSummary: "Jamie would like information about TAFE and entry-level paid work options.",
    status: "offered",
  },
];

export const urgentResources = resources.filter((resource) => resource.urgency === "urgent");
